#!/bin/bash
WORKING_DIR=$1
SRC_DIR=$2
INSTALL_DIR=$3
C_COMPILER=$4
CXX_COMPILER=$5

mkdir -p "$WORKING_DIR"
cd "$WORKING_DIR"
cmake -DCMAKE_INSTALL_PREFIX="$INSTALL_DIR" \
        -DBUILD_SHARED_LIBS=FALSE \
        -DWITH_LIBCXX=Off \
        -DDCMAKE_BUILD_TYPE=Release \
        -DANTLR_BUILD_CPP_TESTS=Off \
        -DFETCHCONTENT_FULLY_DISCONNECTED=On \
        -DCMAKE_CXX_FLAGS="-std=c++17 -DANTLR4CPP_STATIC" \
        -DCMAKE_C_FLAGS="-DANTLR4CPP_STATIC" \
        -DWITH_DEMO=False \
        -DCMAKE_C_COMPILER="$C_COMPILER" \
        -DCMAKE_CXX_COMPILER="$CXX_COMPILER" \
        "$SRC_DIR" && make -j 8 install
